### PR TITLE
correctly pass auth header data during asset creation

### LINKED ISSUE #768: Transfer: Auth header not passed to the API wrapper (for source side)
### Description - What happened? *

When I create an asset with a REST endpoint as the data source and add authentication in the UI, the respective header is not passed to the data source during transfers.

The reason is that the auth information is not passed to the API wrapper on asset creation, specifically it is missing in https://github.com/sovity/edc-ui/blob/cf3b53e99c6876c514a0cea9de3fba71d8ae9885/src/app/core/services/asset-data-source-mapper.ts#L45, although respective fields are defined in `UiDataSource`.

A PR that fixes this is in preparation and will be created later today.

### Expected Behavior *

The auth header is passed to the data source when transferring data.

### Observed Behavior *

The auth header is missing.

### Steps to Reproduce

This can be verified using, for instance, Netcat via `nc -l 8080` on one machine and creating an asset with the data source pointing to this machine's IP on port 8080. When starting a transfer, the headers can be inspected.

### Context Information

> (Added by @AbdullahMuk) Components that were used:
> - edc-ce v9.00
> - edc-ui v4.00

This seems to have been introduced with version 4.0.0.

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by bearn01d**
This PR fixes #768.

To avoid duplicated code, I extracted `getAuthFields` to a dedicated `form-value-utils.ts` file.

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [x] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

**Comment by bearn01d** [comment]
Force-pushed to rebase onto current `main`.

**Review by richardtreier — APPROVED** [review]
LGTM

**Comment by richardtreier** [comment]
We are currently merging many branches. To also get this branch in there before we release, I'll have to recreate it, since I cannot solve merge conflicts on an externally created PR nor push changes

**Comment by richardtreier** [comment]
moved to https://github.com/sovity/edc-ui/pull/772 to resolve merge conflicts.

**Comment by richardtreier** [comment]
Thank you very much for your contribution!

https://github.com/sovity/edc-ui/pull/772 has been merged.

**Pull request closed without merging**
